
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (1, 'Brasil', 0, 1, 'BRA', 'br');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (2, 'Croácia', 0, 1, 'CRO', 'cr');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (3, 'México', 0, 1, 'MEX', 'me');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (4, 'Camarões', 0, 1, 'CAM', 'ca');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (5, 'Espanha', 0, 2, 'ESP', 'es');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (6, 'Holanda', 0, 2, 'HOL', 'ho');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (7, 'Chile', 0, 2, 'CHI', 'ch');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (8, 'Austrália', 0, 2, 'AUS', 'au');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (9, 'Colômbia', 0, 3, 'COL', 'co');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (10, 'Grécia', 0, 3, 'GRE', 'gr');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (11, 'Costa do Marfim', 0, 3, 'CMA', 'cm');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (12, 'Japão', 0, 3, 'JAP', 'ja');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (13, 'Uruguai', 0, 4, 'URU', 'ur');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (14, 'Costa Rica', 0, 4, 'COS', 'cs');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (15, 'Inglaterra', 0, 4, 'ING', 'in');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (16, 'Itália', 0, 4, 'ITA', 'it');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (17, 'Suíça', 0, 5, 'SUI', 'su');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (18, 'Equador', 0, 5, 'EQU', 'eq');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (19, 'França', 0, 5, 'FRA', 'fr');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (20, 'Honduras', 0, 5, 'HON', 'hn');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (21, 'Argentina', 0, 6, 'ARG', 'ar');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (22, 'Bósnia e Herzegovina', 0, 6, 'BOS', 'bo');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (23, 'Irã', 0, 6, 'IRA', 'ir');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (24, 'Nigéria', 0, 6, 'NGR', 'ng');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (25, 'Alemanha', 0, 7, 'ALE', 'al');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (26, 'Portugal', 0, 7, 'POR', 'po');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (27, 'Gana', 0, 7, 'GAN', 'ga');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (28, 'Estados Unidos', 0, 7, 'EUA', 'eu');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (29, 'Bélgica', 0, 8, 'BEL', 'be');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (30, 'Argélia', 0, 8, 'ALG', 'ag');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (31, 'Rússia', 0, 8, 'RUS', 'ru');
INSERT INTO tabela_copa.times (time_id, nome, pontos, grupo_id, abreviatura, sigla) VALUES (32, 'Coréia do Sul', 0, 8, 'CDS', 'cd');